export const HOME = "/"
export const LIBRARY = "/library"
export const PLAYLIST = "/playlists"
export const PLAYLIST_THUMBNAILS = "/playlist"
export const HISTORY = "/history"
// export const WATCH_LATER = "/watch_later"
// export const LIKE_VIDEOS = "/like_videos"
export const PLAYER = "/player"
// export const CONTACT="/#contactModal"

